@startuml
namespace Evidence {
    class DuplicateVoteEvidence << (S,Aquamarine) >> {
        + PubKey crypto.PubKey
        + VoteA *Vote
        + VoteB *Vote

        + String() string
        + Height() int64
        + Time() time.Time
        + Address() []byte
        + Bytes() []byte
        + Hash() []byte
        + Verify(chainID string, pubKey crypto.PubKey) error
        + Equal(ev Evidence) bool
        + ValidateBasic() error

    }

    interface Evidence  {
        + Height() int64
        + Time() time.Time
        + Address() []byte
        + Bytes() []byte
        + Hash() []byte
        + Verify(chainID string, pubKey crypto.PubKey) error
        + Equal( Evidence) bool
        + ValidateBasic() error
        + String() string

    }

}

"Evidence.Evidence" <|-- "implements""Evidence.DuplicateVoteEvidence"

@enduml